[providers.age]
type = "age"
key_file = "/etc/fnox/operational.key"
recipients = [
  "age1drx37m0j265wg7vfwz3t4dfxt9feze3r9qvuys74sd8uny3y2f8slzz75x", # operational
  "age1k2ml2h66ala9a4cq9mpwn5hvx3sylk87kmvq05tpk4cxz3ghwptshfhh4z", # escrow
]

[profiles]

[profiles.observability]

[profiles.observability.secrets]
SCRUB_SALT = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ0dtWmRyNHJMVU1kSkwwQTEvV3ZqSm51b2d1V2dDd3RaKzlkS3JuRmhRClRXTVZPcHdQWFNDaFRGL1NORTd4TkcwZHNGL1lQekFqY21aVTE3Y3h6TEUKLT4gWDI1NTE5IDRGVTVQeG5iMFJEM3RYRTNYdk9zNWRvQk9PeEpBdkFYWnpBVzFDZWoyZ0UKTkZKTzQvVVludHMzR0JyNUtJNUtDOForbGM0YWJyNE0xVDBaOEZxZnR0OAotPiByO0QjKmBJLWdyZWFzZSAxNX47dCAsSVJWCnVBQVZnRXdRWVQyZXVRCi0tLSBZRGRuUGtuQTNtYmpxc1JId3JoUTB3NjFXd1BZNHovUC9BakdkbE1BNitzCrJus2De2YisKspF6X7FzusQZm52XKukwdFWOpXhj5OtZ3KdzhQh4iSZtmea+vtK1VnM98Nh8eEWyCcxWFZ0nQMeCi0vBss0jLB88dk=" }

[profiles.forgejo]

[profiles.forgejo.secrets]
FORGEJO__SECURITY__SECRET_KEY = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWFFXRVM4cUhDeTlEY095dFlvcVVPV3lZeXZlRGlYK05Nb092Z2NtR1c4Ci9TZFd0RDUwdmNFa0x1a3d3NHhkcmF3eFBGdnB2UHp2UjdGWnlRYXpEeEkKLT4gWDI1NTE5IEpNU2dwRmwyTWtVTWxuUWMweU9PeUpJNjRtY2tCNGZ5b09pejR2am5SVmsKdkRLS2RQZmlIUVFONGtKQUVvbTgxNlp0QVhzZWdNVFFzcHBUSzNTYkovdwotPiB0Ii1ncmVhc2UgZjtIZiBHYChCdTt3CnRNTkhrTHNyczFaVUpRdFBQd200RFhrZjdjOGNOcXMxWDgycUdmSzdWWVVNZk80dTk0VWplY1hyZllKUE5rdy8KM1lQdU9STlJhZzNONUNPUzFKeEtNbXVQOHliUWZLaElIcVFLbWk2K0JMSzA3WlRlRDI5d3pQSUc0NXV4eklKWQp1MmsKLS0tIFpuL01ZZDRuckZMTE9wTkx3NEsyS0x3SjNaNTV3elZ0NEROdHpZVXBaQU0K06c46ex0kffIslkreqRH5IRAObR4cPzrbg9kJBQqVb6bjDGnvaAC6L4uH/l+GG+NCLftCOa69W68sO/P7/1h2P2wQ3B22fBuOxg1Sw==" }
FORGEJO__SECURITY__INTERNAL_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRUJTdjQydXo3UWZaYlhCU29aQWcrV3FJN3hNYjUxYit1ZEtWK1gzbW1zCjg3c2dnWm1wZUpoNzhwQ0VrR1NQdlBvdTcramtpbGVsVFBaMmU2QitSa1EKLT4gWDI1NTE5IDJzZVVtai9naWlEaXpjdnAyalowNWtLWEtnajJ3YUNzcU4yQXlsZmNJaVUKNWVGMnJZalE2WjU4NXlpZGRJelpTY2xDeDdwOG1aRnlTVDN1MGlyY0tGYwotPiBhNnUtZ3JlYXNlIC5xdHggN15AIFNrcT8KS0xoSktTTXY5Z0NZQ2FRNWsrcy9XYmJORlhWek5nCi0tLSBJTHFzY3NpazhUaUlEZkpIVTFzaVJnVmhCYWFEK0dXVC8weTZvUmpiMEpnCmkMifE+NbffDs26e0Hge6sno44SVc3Jjmj8l+X4p6Dkb+3OgqbQMwIvtgnhskxD5YDPyAtWhe+jARvWAEBClaAZiPhOP7Ijrsxn4Xg=" }
