[providers.age]
type = "age"
recipients = [
  "age1drx37m0j265wg7vfwz3t4dfxt9feze3r9qvuys74sd8uny3y2f8slzz75x", # operational
  "age1k2ml2h66ala9a4cq9mpwn5hvx3sylk87kmvq05tpk4cxz3ghwptshfhh4z", # escrow
]

[profiles]

[profiles.caddy]

[profiles.caddy.secrets]
TUNNEL_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRTU2ZlJLUk5WKzFZWUxTTU1Senp6VEVvTDA2ajBFVUNrdzNOL1MzcmhNCmpMaEUxVW55MEtpTThiOXh0WFVNQTRsb1A4K0xIOFNienJvS2UzUGhDdUkKLT4gWDI1NTE5IG0xdGQwMXdyejIvT0U5aHhoTzZVZEpGMlBXYnRWMmx6M3dKZzJTYUZTVUEKcktnUjAvOUdtVDhydXQ4UVFwdUlvYTVIcng5QXRyeS9GZmw0cWlSZVB4SQotPiA8dy1ncmVhc2UKN0FXa2k4WXRNYUlIRjNFK3JyaDNHN0w5UHlpeThhOE1OQmVicjU5KzloL0lPaWN3R08rUU9BTWdWRkkKLS0tIGRScDlZMldGREVEY2RhNlFMNDZLM1ZNcGJQMi9pT2N3eFJ0T1NGVnJybm8K+HnpfuhL9du4I8fcq0q1zObrVFfVSKu0dWK63rkyAb5jFI/0ruJoOYN4YpbvnBhm+TDWwkOWgy3M6bMhuXNmXzQb1hs6BrVZFB+DaQ==" }
