[settings.supervisor]
user = "mac"

[daemons.caddy]
user = "svc_caddy"
dir = "/Users/mac/Developer/configuration"
boot_start = true
run = "/usr/local/bin/fnox exec --profile caddy -- /usr/local/bin/caddy run --config Caddyfile"

[daemons.cloudflared]
user = "svc_caddy"
dir = "/Users/mac/Developer/configuration"
boot_start = true
run = "/usr/local/bin/fnox exec --profile caddy -- /usr/local/bin/cloudflared tunnel run"
