[settings]
experimental = true
dotfiles.root = "~/Developer/configuration/"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/git/config" = {}
"~/.config/git/ignore" = {}
"~/.config/mise/config.toml" = {}
"~/.config/zed/keymap.json" = {}
"~/.config/zed/settings.json" = {}
"~/.hermes/SOUL.md" = {}
"~/.hermes/config.yaml" = {}
"~/.hermes/memories/USER.md" = {}
"~/.hermes/skills" = {}
"~/.vimrc" = {}
"~/.zshrc" = {}

[bootstrap.macos.finder]
preferred_view_style = "column"
show_extensions_warning = false
show_pathbar = true

[bootstrap.macos.trackpad]
tap_to_click = true
three_finger_drag = true

[bootstrap.macos.defaults]
NSGlobalDomain = { AppleInterfaceStyleSwitchesAutomatically = true }
"com.apple.WindowManager" = { EnableTiledWindowMargins = true, GloballyEnabled = true }

[tools]
node = "lts"
